// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRecord = "record"

// Record 交易记录
type Record struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                            // id
	UID                 int64     `gorm:"column:uid;not null;comment:电报用户ID" json:"uid"`                                           // 电报用户ID
	JettonWalletAddress string    `gorm:"column:jetton_wallet_address;not null;comment:jetton钱包地址" json:"jetton_wallet_address"`   // jetton钱包地址
	Transaction         string    `gorm:"column:transaction;not null;default:{};comment:交易" json:"transaction"`                    // 交易
	CreateTime          time.Time `gorm:"column:create_time;not null;default:current_timestamp();comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime          time.Time `gorm:"column:update_time;not null;default:current_timestamp();comment:更新时间" json:"update_time"` // 更新时间
}

// TableName Record's table name
func (*Record) TableName() string {
	return TableNameRecord
}
