// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User 用户
type User struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                            // id
	UID                 int64     `gorm:"column:uid;not null;comment:电报用户ID" json:"uid"`                                           // 电报用户ID
	UserName            string    `gorm:"column:user_name;not null;comment:电报用户名" json:"user_name"`                                // 电报用户名
	JettonWalletAddress string    `gorm:"column:jetton_wallet_address;not null;comment:jetton钱包地址" json:"jetton_wallet_address"`   // jetton钱包地址
	PrivateKey          string    `gorm:"column:private_key;not null;comment:TON钱包私钥" json:"private_key"`                          // TON钱包私钥
	Mnemonic            string    `gorm:"column:mnemonic;not null;comment:助记词" json:"mnemonic"`                                    // 助记词
	CreateTime          time.Time `gorm:"column:create_time;not null;default:current_timestamp();comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime          time.Time `gorm:"column:update_time;not null;default:current_timestamp();comment:更新时间" json:"update_time"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
